import bpy
import sys

print("")
print("Blender export scene in GLB Format in file "+sys.argv[-1])

# https://docs.blender.org/api/current/bpy.ops.export_scene.html
bpy.ops.export_scene.gltf(
    filepath=sys.argv[-1],
    check_existing=False,
    export_format='GLB',
    ui_tab='GENERAL',
    export_copyright='',
    export_image_format='AUTO',
    export_texture_dir='', 
    export_keep_originals=False,
    export_texcoords=False, 
    export_normals=False, 
    export_draco_mesh_compression_enable=False, 
    export_draco_mesh_compression_level=6, 
    export_draco_position_quantization=14, 
    export_draco_normal_quantization=10, 
    export_draco_texcoord_quantization=12, 
    export_draco_color_quantization=10, 
    export_draco_generic_quantization=12,
    export_tangents=False,
    export_materials='EXPORT',
    export_original_specular=False,
    export_colors=False,
    use_mesh_edges=False, 
    use_mesh_vertices=True,
    export_cameras=False,
    use_selection=False, 
    use_visible=False, 
    use_renderable=False,
    use_active_collection=False,
    use_active_scene=False,
    export_extras=False,
    export_yup=True, 
    export_apply=True,
    export_animations=False,
    export_frame_range=False,
    export_frame_step=1, 
    export_force_sampling=False, 
    export_nla_strips=False,
    export_nla_strips_merged_animation_name='Animation',
    export_def_bones=False, 
    # export_optimize_animation_size=False, 
    export_anim_single_armature=False, 
    export_current_frame=False, 
    export_skins=False, 
    export_all_influences=False, 
    export_morph=False, 
    export_morph_normal=False, 
    export_morph_tangent=False, 
    export_lights=False, 
    will_save_settings=False,
    filter_glob='*.glb;*.gltf'
    )